---
title: "Dashboard"
---

### NYC Restaurant Inspections

```{r}
library(tidyverse)
library(p8105.datasets)
library(plotly)
data("rest_inspec")
```

```{r}
res_df = rest_inspec |> 
  filter(boro == "Manhattan", 
         critical_flag == "Y", 
         substr(inspection_date,1,4) == "2019",
         !is.na(grade_date),
         !is.na(violation_description),
         !is.na(latitude),
         !is.na(longitude),
         startsWith(`inspection_type`, "Pre-permit")) |> 
  select(-camis, -boro)
```

```{r}
map_pt = res_df |> 
  mutate(text_label = str_c(
    "Name:", dba, "\nCuisine:", cuisine_description)) |> 
  plot_ly(
    x = ~latitude, y = ~longitude, type = "scatter", 
    mode = "markers", color = ~score, text = ~text_label
  )
map_pt
```

```{r}
avg_sc_cuisine = res_df |>
  select(cuisine_description, score) |> 
  group_by(cuisine_description) |> 
  summarize(mean_score = mean(score, na.rm = TRUE)) |> 
  mutate(cuisine_description = fct_reorder(
    cuisine_description, mean_score)) |> 
  plot_ly(
    x = ~cuisine_description, y = ~mean_score, type = "bar", 
    color = ~cuisine_description, colors = "viridis") |> 
  layout(showlegend = FALSE)
avg_sc_cuisine
```

```{r}
sc_cuisine_box = res_df |>
  select(cuisine_description, score) |> 
  mutate(cuisine_description = fct_reorder(
    cuisine_description, score)) |> 
  plot_ly(
    x = ~cuisine_description, y = ~score, type = "box", 
    color = ~cuisine_description, colors = "viridis") |> 
    layout(showlegend = FALSE)
sc_cuisine_box
```

